CREATE KEYSPACE  IF NOT EXISTS TEST 
WITH replication = {'class': 'SimpleStrategy','replication_factor' : 1};

CREATE TABLE IF NOT EXISTS test.STUDENT (
	STUDENTID INT, 
	STUDENTCLASS ASCII,
	STUDENTNAME ASCII,
	ENGLISH_MARKS DECIMAL, 
	MATH_MARKS DECIMAL, 
	IT_MARKS DECIMAL,
	PRIMARY KEY(STUDENTID, STUDENTCLASS)
);

INSERT INTO TEST.STUDENT (STUDENTID, STUDENTCLASS, STUDENTNAME, ENGLISH_MARKS, MATH_MARKS, IT_MARKS)
VALUES(1001, 'CS50', 'John Adams', 76, 92.5, 97);
INSERT INTO TEST.STUDENT (STUDENTID, STUDENTCLASS, STUDENTNAME, ENGLISH_MARKS, MATH_MARKS, IT_MARKS)
VALUES(1002, 'CS50', 'Chuck Norris', 100, 100, 100);
INSERT INTO TEST.STUDENT (STUDENTID, STUDENTCLASS,  STUDENTNAME, ENGLISH_MARKS, MATH_MARKS, IT_MARKS)
VALUES(1003, 'GD1140', 'Bill Gates', 65.3, 78.5, 57);